### PR TITLE
Fix case for blocks directory and change \ to / for includes

### PR DESCRIPTION
**Pull request by Tsutsukakushi**

### CODE REVIEW

**Comment by AlwaysGeeky** [comment]
Thanks for this!

**Comment by Tsutsukakushi** [comment]
@AlwaysGeeky no problem. I got errors while trying to compile and was first going to file a bug report but it was simple enough fix for me to do myself.

Here are the errors that I still have. This is too much for me to decipher.
http://ix.io/ooC

**Comment by AlwaysGeeky** [comment]
@Tsutsukakushi 

It seems that the latest scenery code is not fully compiling on Linux, I will fix this tonight when I get home, shouldn't be too hard. I don't always compile and run the Linux code every day so this happens sometimes when I add big batches of new code.

Sorry I am looking at some automated building systems to help with this soon.

Thanks for your assistance.

**Comment by AlwaysGeeky** [comment]
@Tsutsukakushi

This is fixed now if you get the latest code. Builds on Linux.

**Pull request merged**
